- name: Take prompt input
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false
  - name: TRAINER
    prompt: Please enter trainer name
    private: false
  - name: TARGET
    prompt: Enter course completion target 
    private: false
  tasks: 
  - name: print course information
    ansible.builtin.debug:
      msg: "Hi, I am doing {{COURSE}} and trainer is {{TRAINER}} I want to complete it in {{TARGET}}"
