- name: conditional statments
  hosts: local
  connection: local
  vars:
    number: 120
  tasks:
  - name: check whether number is more then 10 or not
    ansible.builtin.debug:
      msg:  "Print if the number {{number}} is less than 10"
    when: number < 10
  
  - name: print if number is more than 10
    ansible.builtin.debug:
      msg:  "This is {{number}} more than 10"
    when: number >= 10